<a href="https://colab.research.google.com/github/yohan020/data_analysis/blob/main/drive_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [5]:
df_train = pd.read_csv('/train/A.csv', engine='python', on_bad_lines='skip')

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8804 entries, 0 to 8803
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Test_id     8804 non-null   object
 1   Test        8804 non-null   object
 2   PrimaryKey  8804 non-null   object
 3   Age         8804 non-null   object
 4   TestDate    8804 non-null   int64
 5   A1-1        8804 non-null   object
 6   A1-2        8804 non-null   object
 7   A1-3        8804 non-null   object
 8   A1-4        8804 non-null   object
 9   A2-1        8804 non-null   object
 10  A2-2        8804 non-null   object
 11  A2-3        8804 non-null   object
 12  A2-4        8804 non-null   object
 13  A3-1        8804 non-null   object
 14  A3-2        8804 non-null   object
 15  A3-3        8804 non-null   object
 16  A3-4        8804 non-null   object
 17  A3-5        8804 non-null   object
 18  A3-6        8804 non-null   object
 19  A3-7        8804 non-null   object
 20  A4-1        8804 non-null   object
 21  A4-2        8804 non-null   object
 22  A4-3        8804 non-null   object
 23  A4-4        8804 non-null   object
 24  A4-5        8804 non-null   object
 25  A5-1        8804 non-null   object
 26  A5-2        8804 non-null   object
 27  A5-3        8804 non-null   object
 28  A6-1        8804 non-null   int64
 29  A7-1        8804 non-null   int64
 30  A8-1        8804 non-null   int64
 31  A8-2        8804 non-null   int64
 32  A9-1        8804 non-null   int64
 33  A9-2        8804 non-null   int64
 34  A9-3        8804 non-null   int64
 35  A9-4        8804 non-null   int64
 36  A9-5        8804 non-null   int64
dtypes: int64(10), object(27)
memory usage: 2.5+ MB

In [8]:
df_train[9:13].head()

,Test_id,Test,PrimaryKey,Age,TestDate,A1-1,A1-2,A1-3,A1-4,A2-1,...,A5-3,A6-1,A7-1,A8-1,A8-2,A9-1,A9-2,A9-3,A9-4,A9-5
9,0x21E252D2D55222737D1394671AAFACD327D50B99AA1D...,A,0x21E252D2D55222737D1394671AAFACD327D50B99AA1D...,20a,201803,"2,1,1,2,2,2,1,1,1,2,2,1,1,1,1,2,2,2","2,3,1,2,2,3,2,2,2,1,1,3,3,1,1,1,3,3","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","-26,-54,13,7,30,-51,-12,4,78,123,106,-2,22,43,...","1,2,2,3,1,3,3,2,3,2,2,1,3,1,2,1,3,1",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",14,15,3,2,3,8,0,2,2
10,0x669A2301ED2CE93C7DA40AF85844E3A272223FF8340E...,A,0x669A2301ED2CE93C7DA40AF85844E3A272223FF8340E...,20a,201807,"2,2,2,2,1,1,1,1,1,2,1,2,2,1,1,1,2,2","2,3,2,1,3,1,1,3,2,3,2,3,2,2,3,1,1,1","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","-32,-8,-60,-20,-28,-45,-20,-28,-58,-17,-92,-43...","1,3,2,1,3,1,2,2,3,1,1,2,2,2,1,3,3,3",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",10,18,10,0,0,0,1,1,2
11,0x0055A75E64D13B26B242FDF11448842FC943AC9AE700...,A,0x0055A75E64D13B26B242FDF11448842FC943AC9AE700...,20a,201805,"1,2,1,1,1,1,2,2,1,2,2,1,2,2,1,1,2,2","1,2,2,3,1,2,1,3,1,1,3,3,2,1,3,2,3,2","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","65,-9,44,73,39,-46,-8,-51,69,-51,-25,-28,47,3,...","3,1,1,1,2,1,3,3,2,3,2,3,2,1,1,2,2,3",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",12,15,8,0,3,3,1,5,3
12,0xB042BC3F0539149A159E252A7C92051172EC6889AB9A...,A,0xB042BC3F0539149A159E252A7C92051172EC6889AB9A...,20a,201807,"2,2,2,1,1,2,1,2,1,2,1,1,2,1,2,2,1,1","2,1,2,3,1,3,2,3,3,1,3,2,2,1,3,1,2,1","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","-60,-76,-77,-11,-24,-59,-17,-51,-54,-17,-37,-4...","3,2,1,2,2,1,1,2,1,3,3,3,1,2,2,3,3,1",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",10,12,5,0,0,2,0,1,2